### PR TITLE
corrected variable name

### PR DESCRIPTION
**Pull request by mhe-de**

### CODE REVIEW

**Comment by lmangani** [comment]
DOH! Thanks for spotting this @mhe-de

**Comment by mhe-de** [comment]
NP these shitty copy/paste failures 💩

**Comment by lmangani** [comment]
@mhe-de I know its a one liner but it needs the CLA signed. If you prefer not, I ćan push the fix.
Thanks again!

**Comment by mhe-de** [comment]
@lmangani I have signed it twice but it seems like it doesnt change anything. Do i have to create a new PR?

**Comment by lmangani** [comment]
@mhe-de apologies, it normally works if the email is the same you use on github

**Pull request closed without merging**
